services:
  gin_blog:
    image: gin-blog:v1.2.0
    container_name: gin_blog
    ports:
      - "5678:5678"
    volumes:
      - gin_blog_logs:/logs
    depends_on:
      - postgres
      - redis
    networks:
      - gin-blog

  postgres:
    image: postgres:16-alpine
    container_name: postgres_server
    environment:
      POSTGRES_DB: blog
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin123456
    ports:
      - "5432:5432"
    volumes:
      - postgres:/var/lib/postgresql/data
      - ./database/init.sql:/docker-entrypoint-initdb.d/init_script.sql
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 30s
      timeout: 10s
      retries: 3
    restart: always
    networks:
      - gin-blog

  redis:
    image: redis:6.2.6
    container_name: redis_server
    command: redis-server --appendonly yes --requirepass sumingcheng
    ports:
      - "6379:6379"
    volumes:
      - redis:/data
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 30s
      timeout: 10s
      retries: 3
    restart: always
    networks:
      - gin-blog

  prometheus:
    image: prom/prometheus:v2.53.0
    container_name: prometheus
    volumes:
      - ./deploy/prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus_data:/prometheus
    ports:
      - "59090:9090"
    networks:
      - gin-blog
    restart: unless-stopped
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.enable-lifecycle'
    depends_on:
      - gin_blog

  grafana:
    image: grafana/grafana:10.4.4
    container_name: grafana
    volumes:
      - grafana_data:/var/lib/grafana
      - ./deploy/grafana/grafana.ini:/etc/grafana/grafana.ini
      - ./deploy/grafana/provisioning:/etc/grafana/provisioning
    environment:
      GF_SECURITY_ADMIN_PASSWORD: admin123456
      GF_USERS_ALLOW_SIGN_UP: "false"
    ports:
      - "53000:3000"
    networks:
      - gin-blog
    restart: unless-stopped
    depends_on:
      - prometheus

volumes:
  postgres:
  redis:
  gin_blog_logs:
  prometheus_data:
  grafana_data:

networks:
  gin-blog:
    driver: bridge
